# Sieć neuronowa z biblioteką Keras

In [1]:
import tensorflow as tf

from sklearn import datasets
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [2]:
%%html
<iframe src='https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Kosaciec_szczecinkowaty_Iris_setosa.jpg/450px-Kosaciec_szczecinkowaty_Iris_setosa.jpg' 
width = 400 height = 400/iframe>

In [3]:
# zbiór danych do klasyfikacji gatunków irysów na podstawie rozmiarów płatków
iris = datasets.load_iris()

In [4]:
X = iris['data']

In [5]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [7]:
y = iris['target']

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
len(y)

150

In [10]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

#### One hot encoding

Dla zmiennych katergorycznych należy używać takiego przekształcenia. 
Jeśli działalibysmy na początkowych wartościach (0, 1, 2) (traktowanych jako liczby) to dostajemy, że setosa jest bliżej versikolor niż virginica, co nie ma sensu.

In [12]:
y.shape

(150,)

In [13]:
y.reshape(-1,1).shape

(150, 1)

In [11]:
enc = OneHotEncoder()
y_one_hot = enc.fit_transform(y.reshape(-1, 1)).toarray()

In [14]:
y_one_hot

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [15]:
y_one_hot.shape

(150, 3)

### Podział na zbiór trenujący i testowy

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y_one_hot, test_size=0.2, random_state=0)

In [17]:
X_train.shape

(120, 4)

In [18]:
X_test.shape

(30, 4)

In [19]:
y_train.shape

(120, 3)

In [20]:
y_test.shape

(30, 3)

## Sieć neuronowa

In [29]:
# klasa Sequential pozwala na łatwe budowanie sieci złożonej z kolejnych warstw
model = tf.keras.Sequential()
# dodajemy warstwę ukrytą o 4 neuronach
model.add(tf.keras.layers.Dense(5, activation='relu', input_shape=(4,)))
model.add(tf.keras.layers.Dense(15, activation='relu'))

# oraz warstwę wyjściową o 3 (3 bo 3 kategorie)
model.add(tf.keras.layers.Dense(3, activation='softmax'))
# sdg - stochastic gradient descent - optymalizacja metodą największego spadku gradientu
# (inne potencjalnie skuteczniejsze metody: adam, rmsprop)
# funkcja straty - entropia krzyżowa dla wielu klas
# dodatkowo chcemy wyświetlać dokładność (accuracy) jaka część przykładów została zaklasyfikowana poprawnie
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics = ['accuracy'])

In [30]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 5)                 25        
                                                                 
 dense_3 (Dense)             (None, 15)                90        
                                                                 
 dense_4 (Dense)             (None, 3)                 48        
                                                                 
Total params: 163 (652.00 Byte)
Trainable params: 163 (652.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [31]:
# przedyskutować batch_size
model.fit(X_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
12/12 [==============================] - 0s 2ms/step - loss: 1.1561 - accuracy: 0.3667
Epoch 2/100
12/12 [==============================] - 0s 3ms/step - loss: 1.0943 - accuracy: 0.3500
Epoch 3/100
12/12 [==============================] - 0s 1ms/step - loss: 1.0589 - accuracy: 0.6000
Epoch 4/100
12/12 [==============================] - 0s 3ms/step - loss: 1.0048 - accuracy: 0.6917
Epoch 5/100
12/12 [==============================] - 0s 3ms/step - loss: 0.9547 - accuracy: 0.6917
Epoch 6/100
12/12 [==============================] - 0s 3ms/step - loss: 0.9320 - accuracy: 0.6917
Epoch 7/100
12/12 [==============================] - 0s 3ms/step - loss: 0.9045 - accuracy: 0.6917
Epoch 8/100
12/12 [==============================] - 0s 3ms/step - loss: 0.8857 - accuracy: 0.6917
Epoch 9/100
12/12 [==============================] - 0s 1ms/step - loss: 0.8508 - accuracy: 0.6917
Epoch 10/100
12/12 [==============================] - 0s 3ms/step - loss: 0.8213 - accuracy: 0.6917
Epoch 11/

12/12 [==============================] - 0s 3ms/step - loss: 0.1755 - accuracy: 0.9333
Epoch 84/100
12/12 [==============================] - 0s 1ms/step - loss: 0.1504 - accuracy: 0.9583
Epoch 85/100
12/12 [==============================] - 0s 2ms/step - loss: 0.1679 - accuracy: 0.9417
Epoch 86/100
12/12 [==============================] - 0s 3ms/step - loss: 0.1641 - accuracy: 0.9417
Epoch 87/100
12/12 [==============================] - 0s 3ms/step - loss: 0.1689 - accuracy: 0.9500
Epoch 88/100
12/12 [==============================] - 0s 2ms/step - loss: 0.1497 - accuracy: 0.9500
Epoch 89/100
12/12 [==============================] - 0s 1ms/step - loss: 0.1665 - accuracy: 0.9333
Epoch 90/100
12/12 [==============================] - 0s 1ms/step - loss: 0.1471 - accuracy: 0.9583
Epoch 91/100
12/12 [==============================] - 0s 2ms/step - loss: 0.1611 - accuracy: 0.9417
Epoch 92/100
12/12 [==============================] - 0s 3ms/step - loss: 0.1813 - accuracy: 0.9250
Epoch 93/100


In [25]:
model.evaluate(X_train, y_train)

4/4 [==============================] - 0s 0s/step - loss: 0.1581 - accuracy: 0.9583


[0.15807758271694183, 0.9583333134651184]

In [26]:
model.evaluate(X_test, y_test)

1/1 [==============================] - 0s 31ms/step - loss: 0.1520 - accuracy: 1.0000


[0.15204794704914093, 1.0]

In [27]:
model.predict(X_test)

1/1 [==============================] - 0s 85ms/step


array([[8.48814216e-06, 4.01468240e-02, 9.59844708e-01],
       [7.41990656e-03, 8.62037003e-01, 1.30543053e-01],
       [9.92619693e-01, 7.38031929e-03, 3.31274297e-09],
       [1.37156076e-06, 2.70368066e-02, 9.72961783e-01],
       [9.85234857e-01, 1.47651536e-02, 4.93177623e-08],
       [6.12404619e-07, 1.06026623e-02, 9.89396691e-01],
       [9.87439752e-01, 1.25601925e-02, 2.62329642e-08],
       [4.29531978e-03, 8.74537945e-01, 1.21166721e-01],
       [2.06446601e-03, 7.81960070e-01, 2.15975508e-01],
       [1.63555928e-02, 9.36401427e-01, 4.72429395e-02],
       [5.74031947e-06, 2.97128838e-02, 9.70281303e-01],
       [7.89757352e-03, 9.04821277e-01, 8.72812271e-02],
       [2.21101195e-03, 6.31376028e-01, 3.66413057e-01],
       [2.65369797e-03, 7.82449901e-01, 2.14896366e-01],
       [1.95847638e-03, 6.18440926e-01, 3.79600614e-01],
       [9.85806584e-01, 1.41934212e-02, 4.22688622e-08],
       [3.08820955e-03, 7.06647456e-01, 2.90264308e-01],
       [2.09347298e-03, 5.04927